import { useEffect, useRef } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import BrainArtwork from '../components/BrainArtwork';
import MagicBento from '../components/MagicBento';
import './CurrentlyCooking.css';
import './BrainEntry.css';
import './ThingsIKnow.css';

gsap.registerPlugin(ScrollTrigger);

/**
 * THOUGHTS GENERATED BY NEURAL FIRING
 *
 * Pacing progression strictly tied to scroll depth:
 * - Depth 0% (Calm): Initial slow, peaceful subconscious thoughts drifting very slowly.
 * - Depth 20% - 40%: Density gradually rises, gentle speed increase.
 * - Depth 60% - 75%: Thoughts become more frequent from all quadrants.
 * - Depth 85% - 92%: Brain overload, thoughts move noticeably faster and more chaotically.
 * - Depth 100%: Sudden black flash -> collapse into center!
 */
const NEURAL_THOUGHTS = [
  // ── DEPTH 0% - 20%: CALM SUBCONSCIOUS (Very slow, quiet, solitary thoughts) ──
  {
    id: 't-movie-1',
    text: 'what movie should i watch tonight...',
    className: 'neural-thought depth-mid tint-warm',
    in: 39.0,
    peak: 45.0,
    out: 51.5,
    from: { x: 140, y: -140, z: -240, scale: 0.8, rot: -1.5 },
    to:   { x: 170, y: -155, z: 60,   scale: 1.05, rot: -0.8 },
  },
  {
    id: 't-sleep-soon',
    text: 'maybe i should sleep',
    className: 'neural-thought depth-mid',
    in: 44.0,
    peak: 49.5,
    out: 55.5,
    from: { x: -160, y: 160, z: -250, scale: 0.8, rot: 1.8 },
    to:   { x: -190, y: 180, z: 50,   scale: 1.05, rot: 1.0 },
  },
  {
    id: 't-what-doing',
    text: 'what was i doing?',
    className: 'neural-thought depth-mid',
    in: 48.5,
    peak: 53.5,
    out: 59.5,
    from: { x: 150, y: 120, z: -260, scale: 0.8, rot: -1.5 },
    to:   { x: 180, y: 135, z: 70,   scale: 1.08, rot: -0.8 },
  },
  {
    id: 't-just-one-ep',
    text: 'one more episode',
    className: 'neural-thought depth-mid tint-distract',
    in: 52.5,
    peak: 57.0,
    out: 63.0,
    from: { x: -210, y: -40, z: -260, scale: 0.82, rot: -1.8 },
    to:   { x: -250, y: -50, z: 80,   scale: 1.1,  rot: -1.0 },
  },
  {
    id: 't-record-1',
    text: 'did i submit the record?',
    className: 'neural-thought depth-far',
    in: 55.0,
    peak: 59.5,
    out: 65.5,
    from: { x: 180, y: 170, z: -320, scale: 0.75, rot: 2.0 },
    to:   { x: 220, y: 190, z: 60,   scale: 1.0,  rot: 1.2 },
  },

  // ── DEPTH 40%: CURIOUS / DENSITY INCREASING ──
  {
    id: 't-assign-1',
    text: 'wait i have an assignment',
    className: 'neural-thought depth-mid',
    in: 58.0,
    peak: 62.0,
    out: 67.5,
    from: { x: -180, y: -110, z: -260, scale: 0.85, rot: 2.0 },
    to:   { x: -230, y: -130, z: 100,  scale: 1.18, rot: 1.2 },
  },
  {
    id: 't-spacing-4px',
    text: 'the spacing is 4px off',
    className: 'neural-thought depth-near',
    in: 60.5,
    peak: 64.5,
    out: 69.5,
    from: { x: 40, y: -190, z: -240, scale: 0.85, rot: 1.2 },
    to:   { x: 50, y: -230, z: 120,  scale: 1.22, rot: 0.5 },
  },
  {
    id: 't-code-working',
    text: 'why is this code not working',
    className: 'neural-thought depth-mid',
    in: 62.8,
    peak: 66.8,
    out: 71.8,
    from: { x: -190, y: 130, z: -280, scale: 0.8, rot: 1.5 },
    to:   { x: -240, y: 155, z: 110,  scale: 1.16, rot: 0.8 },
  },
  {
    id: 't-what-song',
    text: 'what song fits this?',
    className: 'neural-thought depth-mid tint-music',
    in: 64.8,
    peak: 68.5,
    out: 73.5,
    from: { x: 210, y: 30, z: -240, scale: 0.85, rot: -2.0 },
    to:   { x: 260, y: 35, z: 120,  scale: 1.2,  rot: -1.0 },
  },

  // ── DEPTH 60%: BUSIER / DRIFTING FASTER ──
  {
    id: 't-semicolon',
    text: 'oh. semicolon.',
    className: 'neural-thought depth-near weight-bold',
    in: 66.8,
    peak: 70.2,
    out: 75.0,
    from: { x: -80, y: 40, z: -200, scale: 0.9, rot: -1.5 },
    to:   { x: -100, y: 55, z: 180, scale: 1.3, rot: -0.8 },
  },
  {
    id: 't-exam-3days',
    text: 'exam in 3 days',
    className: 'neural-thought depth-mid tint-urgent',
    in: 68.8,
    peak: 72.2,
    out: 77.0,
    from: { x: -140, y: -160, z: -220, scale: 0.9, rot: -2.0 },
    to:   { x: -180, y: -195, z: 150,  scale: 1.28, rot: -1.0 },
  },
  {
    id: 't-lana',
    text: 'lana del rey',
    className: 'neural-thought depth-near tint-music weight-medium',
    in: 70.8,
    peak: 74.0,
    out: 78.8,
    from: { x: 150, y: -110, z: -200, scale: 0.9, rot: 1.8 },
    to:   { x: 195, y: -130, z: 160, scale: 1.3, rot: 1.0 },
  },
  {
    id: 't-one-change',
    text: 'one more change',
    className: 'neural-thought depth-near weight-bold',
    in: 72.2,
    peak: 75.5,
    out: 80.2,
    from: { x: 0, y: 10, z: -180, scale: 0.95, rot: -1.0 },
    to:   { x: 10, y: -10, z: 220, scale: 1.45, rot: 0.2 },
  },
  {
    id: 't-better-anim',
    text: 'this animation could be better',
    className: 'neural-thought depth-mid tint-warm',
    in: 73.8,
    peak: 77.0,
    out: 81.8,
    from: { x: -220, y: 60, z: -200, scale: 0.85, rot: 1.8 },
    to:   { x: -270, y: 75, z: 150,  scale: 1.25, rot: 1.0 },
  },

  // ── DEPTH 75%: OVERTHINKING BEGINS ──
  {
    id: 't-rebuild-this',
    text: 'should i rebuild this?',
    className: 'neural-thought depth-near weight-medium',
    in: 75.6,
    peak: 78.6,
    out: 83.2,
    from: { x: 210, y: -70, z: -190, scale: 0.9, rot: -2.2 },
    to:   { x: 260, y: -90, z: 170,  scale: 1.32, rot: -1.2 },
  },
  {
    id: 't-shinchan',
    text: 'SHIN CHAN',
    className: 'neural-thought depth-near tint-shinchan weight-bold',
    in: 77.2,
    peak: 80.2,
    out: 84.6,
    from: { x: 80, y: -40, z: -190, scale: 0.95, rot: 3.0 },
    to:   { x: 105, y: -50, z: 240, scale: 1.45, rot: 1.8 },
  },
  {
    id: 't-new-project',
    text: 'NEW PROJECT IDEA',
    className: 'neural-thought depth-near tint-warm weight-bold',
    in: 78.8,
    peak: 81.6,
    out: 85.8,
    from: { x: 40, y: -160, z: -170, scale: 0.95, rot: 1.8 },
    to:   { x: 50, y: -195, z: 210,  scale: 1.4,  rot: 0.8 },
  },
  {
    id: 't-no-projects',
    text: 'NO MORE PROJECTS',
    className: 'neural-thought depth-near tint-urgent weight-bold',
    in: 80.2,
    peak: 83.0,
    out: 86.8,
    from: { x: -50, y: 170, z: -170, scale: 0.95, rot: -2.2 },
    to:   { x: -65, y: 205, z: 210,  scale: 1.4,  rot: -1.0 },
  },
  {
    id: 't-actually',
    text: 'actually...',
    className: 'neural-thought depth-mid tint-warm',
    in: 81.6,
    peak: 84.2,
    out: 87.5,
    from: { x: -70, y: -20, z: -150, scale: 0.9, rot: 1.5 },
    to:   { x: -95, y: -25, z: 170,  scale: 1.28, rot: 0.8 },
  },

  // ── DEPTH 85% - 92%: COGNITIVE LOAD & OVERLOAD (Fast, chaotic, all directions) ──
  {
    id: 't-focus-1',
    text: 'okay focus',
    className: 'neural-thought depth-near weight-bold',
    in: 83.0,
    peak: 85.4,
    out: 88.5,
    from: { x: -110, y: -120, z: -160, scale: 0.95, rot: 1.5 },
    to:   { x: -140, y: -150, z: 180,  scale: 1.35, rot: 0.8 },
  },
  {
    id: 't-java-main',
    text: 'JAVA',
    className: 'neural-thought depth-near tint-urgent weight-bold',
    in: 84.0,
    peak: 86.2,
    out: 88.8,
    from: { x: -180, y: -80, z: -150, scale: 1.0, rot: -1.8 },
    to:   { x: -220, y: -100, z: 200, scale: 1.4, rot: -0.8 },
  },
  {
    id: 't-record-main',
    text: 'RECORD',
    className: 'neural-thought depth-near tint-urgent weight-bold',
    in: 84.8,
    peak: 86.8,
    out: 88.8,
    from: { x: 170, y: 90, z: -140, scale: 1.0, rot: 2.0 },
    to:   { x: 210, y: 110, z: 200, scale: 1.4, rot: 1.0 },
  },
  {
    id: 't-exam-main',
    text: 'EXAM',
    className: 'neural-thought depth-near tint-urgent weight-bold',
    in: 85.5,
    peak: 87.2,
    out: 89.0,
    from: { x: 120, y: -130, z: -140, scale: 1.0, rot: -1.8 },
    to:   { x: 150, y: -160, z: 210,  scale: 1.45, rot: -0.8 },
  },
  {
    id: 't-assign-main',
    text: 'ASSIGNMENT',
    className: 'neural-thought depth-near tint-urgent weight-bold',
    in: 86.2,
    peak: 87.8,
    out: 89.0,
    from: { x: -160, y: 120, z: -140, scale: 1.0, rot: 2.0 },
    to:   { x: -200, y: 145, z: 210,  scale: 1.45, rot: 1.0 },
  },
  {
    id: 't-focus-2',
    text: 'NO SERIOUSLY FOCUS',
    className: 'neural-thought depth-near tint-urgent weight-bold',
    in: 86.8,
    peak: 88.2,
    out: 89.0,
    from: { x: 0, y: -50, z: -140, scale: 1.05, rot: -1.5 },
    to:   { x: 0, y: -65, z: 220,  scale: 1.5,  rot: -0.5 },
  },
  {
    id: 't-too-many',
    text: 'TOO MANY THOUGHTS',
    className: 'neural-thought depth-near tint-urgent weight-bold',
    in: 87.4,
    peak: 88.6,
    out: 89.0,
    from: { x: 0, y: 60, z: -130, scale: 1.05, rot: 1.2 },
    to:   { x: 0, y: 75, z: 210,  scale: 1.5,  rot: 0.2 },
  },
];

/* ─────────────────────────────────────────────────────────────────
   THOUGHTS & KNOWLEDGE REPERTOIRE (Visible immediately upon collapse)
───────────────────────────────────────────────────────────────── */
const KNOWLEDGE_ITEMS = [
  { id: 'photography', text: 'PHOTOGRAPHY', x: -260, y: -230, rot: -2.5, scale: 1.0 },
  { id: 'videography', text: 'VIDEOGRAPHY', x: 280, y: -220, rot: 2.5, scale: 1.0 },
  { id: 'c', text: 'C', x: -80, y: -190, rot: 2.0, scale: 1.0 },
  { id: 'video-editing', text: 'VIDEO EDITING', x: -280, y: -140, rot: -2.0, scale: 1.0 },
  { id: 'java', text: 'JAVA', x: 250, y: -140, rot: -2.0, scale: 1.0 },
  { id: 'vibe-coding', text: 'VIBE CODING', x: 20, y: -110, rot: 1.5, scale: 1.0 },
];

const RANDOM_THOUGHTS = [
  { id: 'rt-1', text: 'maybe i should sleep', x: 10, y: -270, rot: 1, scale: 1.05 },
  { id: 'rt-2', text: 'one more episode', x: 270, y: -240, rot: 2, scale: 1.05 },
  { id: 'rt-3', text: 'what was i doing?', x: 0, y: -130, rot: -1, scale: 1.08 },
  { id: 'rt-4', text: 'SHIN CHAN', x: 350, y: -10, rot: -2, scale: 1.1 },
  { id: 'rt-5', text: 'this animation could be better', x: -220, y: 120, rot: -2, scale: 1.05 },
  { id: 'rt-6', text: 'exam in 3 days', x: 270, y: 130, rot: 2, scale: 1.1 },
  { id: 'rt-7', text: 'what movie should i watch tonight...', x: -300, y: 240, rot: 1, scale: 1.05 },
  { id: 'rt-8', text: 'NO SERIOUSLY FOCUS', x: 40, y: 270, rot: -1, scale: 1.12 },
  { id: 'rt-9', text: 'one more change', x: 150, y: 30, rot: 2, scale: 1.05 },
  { id: 'rt-10', text: 'NEW PROJECT IDEA', x: -170, y: 40, rot: -2, scale: 1.08 },
  { id: 'rt-11', text: 'did i submit the record?', x: -470, y: -200, rot: -4, scale: 0.96 },
  { id: 'rt-12', text: 'the spacing is 4px off', x: 470, y: -210, rot: 3, scale: 0.98 },
  { id: 'rt-13', text: 'why is this code not working', x: -190, y: -210, rot: -2, scale: 0.96 },
  { id: 'rt-14', text: 'oh. semicolon.', x: 190, y: -180, rot: 2, scale: 1.0 },
  { id: 'rt-15', text: 'lana del rey', x: -390, y: -90, rot: 3, scale: 0.98 },
  { id: 'rt-16', text: 'what song fits this?', x: 390, y: -90, rot: -4, scale: 0.96 },
  { id: 'rt-17', text: 'actually...', x: -110, y: -120, rot: -2, scale: 0.98 },
  { id: 'rt-18', text: 'should i rebuild this?', x: 180, y: -50, rot: 2, scale: 0.98 },
  { id: 'rt-19', text: 'NO MORE PROJECTS', x: -450, y: 70, rot: -3, scale: 1.0 },
  { id: 'rt-20', text: 'RECORD', x: 460, y: 70, rot: 4, scale: 1.0 },
  { id: 'rt-21', text: 'okay focus', x: -20, y: 80, rot: 1, scale: 0.98 },
  { id: 'rt-22', text: 'ASSIGNMENT', x: -370, y: -20, rot: 3, scale: 1.08 },
  { id: 'rt-23', text: 'EXAM', x: 240, y: -340, rot: 3, scale: 0.88 },
  { id: 'rt-24', text: 'wait i have an assignment', x: -260, y: -340, rot: 4, scale: 0.9 },
];

const ALL_PHYSICS_THOUGHTS = [
  ...KNOWLEDGE_ITEMS.map((k, i) => ({
    id: k.id,
    x: k.x,
    y: k.y,
    isKnowledge: true,
    radius: 150,
    radiusSq: 150 * 150,
    maxPull: 14,
    phaseX: i * 0.75,
    phaseY: i * 0.9,
    phaseRot: i * 1.1,
  })),
  ...RANDOM_THOUGHTS.map((r, i) => ({
    id: r.id,
    x: r.x,
    y: r.y,
    isKnowledge: false,
    radius: 120,
    radiusSq: 120 * 120,
    maxPull: 9,
    phaseX: (i + 6) * 0.75,
    phaseY: (i + 6) * 0.9,
    phaseRot: (i + 6) * 1.1,
  })),
];

export default function BrainEntry() {
  const containerRef = useRef(null);
  const stageRef = useRef(null);
  const journeyWrapperRef = useRef(null);
  const cameraRigRef = useRef(null);

  // Background atmosphere
  const atmosphereRef = useRef(null);

  // Layer 1: Currently Cooking in depth space
  const cookingDepthRef = useRef(null);
  const steamWrapRef = useRef(null);
  const cookingParticlesRef = useRef(null);

  // Layer 2: Real Anatomical Brain Centerpiece
  const brainDepthRef = useRef(null);

  // Layer 3: The Living Biological Neural Network Environment (4 Depth Tiers)
  const neuralWorldRef = useRef(null);
  const neuralFarRef = useRef(null);
  const neuralMidRef = useRef(null);
  const neuralForeRef = useRef(null);
  const neuralMicroRef = useRef(null);

  // Biological Somas
  const soma1Ref = useRef(null);
  const soma2Ref = useRef(null);
  const soma3Ref = useRef(null);
  const soma4Ref = useRef(null);
  const soma5Ref = useRef(null);
  const soma6Ref = useRef(null);
  const soma7Ref = useRef(null);
  const soma8Ref = useRef(null);
  const soma9Ref = useRef(null);
  const soma10Ref = useRef(null);

  // Synaptic Boutons
  const syn1Ref = useRef(null);
  const syn2Ref = useRef(null);
  const syn3Ref = useRef(null);
  const syn4Ref = useRef(null);
  const syn5Ref = useRef(null);
  const syn6Ref = useRef(null);

  // Electrical Signal Pulses (GPU transform driven)
  const sig1Ref = useRef(null);
  const sig2Ref = useRef(null);
  const sig3Ref = useRef(null);
  const sig4Ref = useRef(null);
  const sig5Ref = useRef(null);
  const sig6Ref = useRef(null);
  const sig7Ref = useRef(null);
  const sig8Ref = useRef(null);

  // Layer 4: Editorial warnings
  const enterBrainRef = useRef(null);
  const sureRef = useRef(null);
  const reallySureRef = useRef(null);
  const mightBeBugsRef = useRef(null);
  const goingInRef = useRef(null);

  // Layer 5: "I AM INSIDE." badge
  const insideRef = useRef(null);

  // Layer 7: Bottom Warning System (Subtle, Modern Minimal Typography)
  const warningRef = useRef(null);
  const w1Ref = useRef(null);
  const w2Ref = useRef(null);
  const w3Ref = useRef(null);
  const w4Ref = useRef(null);
  const w5Ref = useRef(null);
  const w6Ref = useRef(null);
  const w7Ref = useRef(null);

  // Layer 8: Very Short Black Screen Flash (Brain crash interruption before collapse)
  const blackFlashRef = useRef(null);

  // Layer 9: Silence Blackout (Final transition hold)
  const blackoutRef = useRef(null);

  // Thought references
  const thoughtRefs = useRef({});

  // Layer 10: Bento & Immediate Thought Field
  const bentoSectionRef = useRef(null);
  const bentoHeaderRef = useRef(null);
  const bentoTagRef = useRef(null);
  const bentoTitleRef = useRef(null);
  const bentoSubtitleRef = useRef(null);
  const bentoGridWrapRef = useRef(null);
  const thoughtFieldRef = useRef(null);

  const fallingThoughtWrapperRefs = useRef({});
  const fallingThoughtInnerRefs = useRef({});
  const fallingTrailRefs = useRef({});
  const randomThoughtWrapperRefs = useRef({});
  const randomThoughtInnerRefs = useRef({});

  const scrollProgressRef = useRef(0);
  const isSectionVisibleRef = useRef(false);
  const physicsRunningRef = useRef(false);
  const startPhysicsRef = useRef(null);
  const stopPhysicsRef = useRef(null);
  const stageCenterRef = useRef({ x: 0, y: 0 });

  // ── AUTONOMOUS FLOATING & MAGNETIC PHYSICS LOOP ──
  // Runs on-demand via requestAnimationFrame ONLY when thought field is active (progress: 0.88 -> 0.975)
  useEffect(() => {
    let mouse = { x: -9999, y: -9999, active: false };
    let rafId = null;

    const physicsState = new Map();
    ALL_PHYSICS_THOUGHTS.forEach((t) => {
      physicsState.set(t.id, {
        currX: 0,
        currY: 0,
        currRot: 0,
      });
    });

    const updateCenter = () => {
      stageCenterRef.current = {
        x: window.innerWidth * 0.5,
        y: window.innerHeight * 0.5,
      };
    };
    updateCenter();

    const onPointerMove = (e) => {
      mouse.x = e.clientX;
      mouse.y = e.clientY;
      mouse.active = true;
    };

    const onPointerLeave = () => {
      mouse.active = false;
    };

    const updatePhysics = (time) => {
      if (!physicsRunningRef.current || !isSectionVisibleRef.current) {
        physicsRunningRef.current = false;
        rafId = null;
        return;
      }

      const progress = scrollProgressRef.current;
      // Stop loop when outside the active thought field window
      if (progress < 0.635 || progress > 0.935) {
        physicsRunningRef.current = false;
        rafId = null;
        return;
      }

      const centerX = stageCenterRef.current.x;
      const centerY = stageCenterRef.current.y;
      const relMouseX = mouse.active ? mouse.x - centerX : -99999;
      const relMouseY = mouse.active ? mouse.y - centerY : -99999;

      const THOUGHT_START_PROGRESS = {
        'photography': 0.640,
        'videography': 0.690,
        'video-editing': 0.740,
        'c': 0.790,
        'java': 0.840,
        'vibe-coding': 0.890,
      };

      // Random thoughts drift gracefully while cloud is active, then fade out (72% -> 82%)
      const randomDamping = progress > 0.72 ? Math.max(0, 1 - (progress - 0.72) / 0.10) : 1;
      const isMagneticActive = mouse.active;

      let magneticCount = 0;
      const MAX_MAGNETIC_THOUGHTS = 10;

      for (let i = 0; i < ALL_PHYSICS_THOUGHTS.length; i++) {
        const t = ALL_PHYSICS_THOUGHTS[i];
        const innerEl = t.isKnowledge
          ? fallingThoughtInnerRefs.current[t.id]
          : randomThoughtInnerRefs.current[t.id];
        const state = physicsState.get(t.id);
        if (!innerEl || !state) continue;

        // When a knowledge thought is selected and starts falling, zero its local drift
        if (t.isKnowledge) {
          const startP = THOUGHT_START_PROGRESS[t.id] || 0.99;
          if (progress >= startP) {
            innerEl.style.transform = 'translate3d(0px, 0px, 0px) rotate(0deg)';
            continue;
          }
        }

        const effectiveDamping = t.isKnowledge ? 1.0 : randomDamping;
        if (effectiveDamping <= 0) {
          innerEl.style.transform = 'translate3d(0px, 0px, 0px) rotate(0deg)';
          continue;
        }

        // Continuous organic floating sine wave (precalculated static phase offsets)
        const autoX = Math.sin(time * 0.0008 + t.phaseX) * 5.0 * effectiveDamping;
        const autoY = Math.cos(time * 0.0006 + t.phaseY) * 3.8 * effectiveDamping;
        const autoRot = Math.sin(time * 0.0005 + t.phaseRot) * 1.0 * effectiveDamping;

        let targetX = autoX;
        let targetY = autoY;
        let targetRot = autoRot;

        // Bounding box filter before distance calculation, capped to 10 nearest thoughts
        if (isMagneticActive && effectiveDamping > 0.1 && magneticCount < MAX_MAGNETIC_THOUGHTS) {
          const dx = relMouseX - t.x;
          const dy = relMouseY - t.y;

          if (Math.abs(dx) < t.radius && Math.abs(dy) < t.radius) {
            const distSq = dx * dx + dy * dy;
            if (distSq < t.radiusSq && distSq > 1) {
              const dist = Math.sqrt(distSq);
              const prox = 1 - dist / t.radius;
              const force = prox * prox * t.maxPull * effectiveDamping;
              targetX += (dx / dist) * force;
              targetY += (dy / dist) * force;
              targetRot += (dx > 0 ? 1 : -1) * 1.2 * prox;
              magneticCount++;
            }
          }
        }

        // Smooth spring damping (lerp with 0.1)
        state.currX += (targetX - state.currX) * 0.1;
        state.currY += (targetY - state.currY) * 0.1;
        state.currRot += (targetRot - state.currRot) * 0.1;

        innerEl.style.transform = `translate3d(${state.currX.toFixed(1)}px, ${state.currY.toFixed(1)}px, 0) rotate(${state.currRot.toFixed(2)}deg)`;
      }

      rafId = requestAnimationFrame(updatePhysics);
    };

    const startPhysics = () => {
      if (physicsRunningRef.current) return;
      if (!isSectionVisibleRef.current) return;
      updateCenter();
      physicsRunningRef.current = true;
      rafId = requestAnimationFrame(updatePhysics);
    };

    const stopPhysics = () => {
      physicsRunningRef.current = false;
      if (rafId) {
        cancelAnimationFrame(rafId);
        rafId = null;
      }
    };

    startPhysicsRef.current = startPhysics;
    stopPhysicsRef.current = stopPhysics;

    window.addEventListener('pointermove', onPointerMove, { passive: true });
    window.addEventListener('pointerleave', onPointerLeave, { passive: true });
    window.addEventListener('resize', updateCenter, { passive: true });

    // IntersectionObserver to pause physics when section is out of viewport
    const observer = new IntersectionObserver(([entry]) => {
      isSectionVisibleRef.current = entry.isIntersecting;
      if (!entry.isIntersecting) {
        stopPhysics();
      } else {
        const prog = scrollProgressRef.current;
        if (prog >= 0.64 && prog <= 0.93) {
          startPhysics();
        }
      }
    }, { threshold: 0 });

    if (containerRef.current) {
      observer.observe(containerRef.current);
    }

    const onVisibilityChange = () => {
      if (document.hidden) {
        stopPhysics();
      } else {
        const prog = scrollProgressRef.current;
        if (isSectionVisibleRef.current && prog >= 0.64 && prog <= 0.93) {
          startPhysics();
        }
      }
    };
    document.addEventListener('visibilitychange', onVisibilityChange);

    return () => {
      window.removeEventListener('pointermove', onPointerMove);
      window.removeEventListener('pointerleave', onPointerLeave);
      window.removeEventListener('resize', updateCenter);
      document.removeEventListener('visibilitychange', onVisibilityChange);
      observer.disconnect();
      stopPhysics();
    };
  }, []);

  // ── MASTER GSAP TIMELINE ──
  useEffect(() => {
    const container = containerRef.current;
    const stage = stageRef.current;
    if (!container || !stage) return;

    const ctx = gsap.context(() => {
      const tl = gsap.timeline({
        scrollTrigger: {
          trigger: container,
          start: 'top top',
          end: 'bottom bottom',
          pin: stage,
          scrub: 0.8, // Smooth, buttery cinematic interpolation
          invalidateOnRefresh: true,
          onUpdate: (self) => {
            scrollProgressRef.current = self.progress;
            if (typeof window !== 'undefined') window.__brainProgress = self.progress;

            // Manage physics loop on demand (active during floating thought cloud and extraction)
            if (self.progress >= 0.58 && self.progress <= 0.93) {
              if (startPhysicsRef.current) startPhysicsRef.current();
            } else {
              if (stopPhysicsRef.current) stopPhysicsRef.current();
            }

            if (bentoSectionRef.current) {
              if (self.progress >= 0.93) {
                bentoSectionRef.current.classList.add('is-active');
              } else {
                bentoSectionRef.current.classList.remove('is-active');
              }
            }
          },
        },
      });

      /* ─────────────────────────────────────────────────────────────
         INITIAL SETUP (Pure GPU transforms & opacities)
      ───────────────────────────────────────────────────────────── */
      gsap.set(journeyWrapperRef.current, {
        scale: 1,
        z: 0,
        opacity: 1,
        force3D: true,
      });

      // Camera Rig holding depth layers
      gsap.set(cameraRigRef.current, {
        scale: 1.0,
        z: 0,
        transformOrigin: '50% 50%',
        force3D: true,
      });

      // Layer 1: Currently Cooking
      gsap.set(cookingDepthRef.current, {
        opacity: 1,
        scale: 1,
        y: 0,
        z: 0,
        force3D: true,
      });
      gsap.set(steamWrapRef.current, { opacity: 0.2, scale: 0.9, y: 15, force3D: true });
      gsap.set(cookingParticlesRef.current, { opacity: 0.3, y: 0, force3D: true });

      // Layer 2: Whole Brain Artwork (approaches, centered)
      gsap.set(brainDepthRef.current, {
        opacity: 0,
        scale: 0.85,
        y: 0,
        z: 0,
        transformOrigin: '50% 48%',
        force3D: true,
      });

      // Background atmospheric aura
      gsap.set(atmosphereRef.current, { opacity: 0.2, scale: 0.8, force3D: true });

      // Layer 3: Living Biological Neural Network Environment (4 Depth Tiers)
      gsap.set(neuralWorldRef.current, { opacity: 0, force3D: true });
      gsap.set(neuralFarRef.current, { scale: 0.88, z: -220, opacity: 0.55, force3D: true });
      gsap.set(neuralMidRef.current, { scale: 1.0, z: 0, opacity: 0.92, force3D: true });
      gsap.set(neuralForeRef.current, { scale: 1.25, z: 180, opacity: 0.65, force3D: true });
      gsap.set(neuralMicroRef.current, { scale: 1.35, z: 240, opacity: 0.7, force3D: true });

      // Signals & Synapses initial state
      gsap.set(
        [
          sig1Ref.current,
          sig2Ref.current,
          sig3Ref.current,
          sig4Ref.current,
          sig5Ref.current,
          sig6Ref.current,
          sig7Ref.current,
          sig8Ref.current,
        ],
        { opacity: 0, scale: 0, force3D: true }
      );

      // Layer 4: Editorial warnings
      gsap.set(
        [
          enterBrainRef.current,
          sureRef.current,
          reallySureRef.current,
          mightBeBugsRef.current,
          goingInRef.current,
        ],
        {
          opacity: 0,
          y: 8,
          scale: 0.99,
          force3D: true,
        }
      );

      // Layer 5: "I AM INSIDE." badge
      gsap.set(insideRef.current, {
        opacity: 0,
        scale: 0.96,
        y: 12,
        z: -100,
        force3D: true,
      });

      // Layer 7: Bottom Warning System (Small, minimal, modern)
      gsap.set(warningRef.current, { opacity: 0, y: 15, force3D: true });
      gsap.set(
        [w1Ref.current, w2Ref.current, w3Ref.current, w4Ref.current, w5Ref.current, w6Ref.current, w7Ref.current],
        { opacity: 0, y: 6, force3D: true }
      );

      // Layer 8: Very Short Black Screen Flash
      gsap.set(blackFlashRef.current, { opacity: 0, force3D: true });

      // Layer 9: Blackout
      gsap.set(blackoutRef.current, { opacity: 0, force3D: true });

      // Layer 10: Bento & Thought Field Initial State
      gsap.set(bentoSectionRef.current, { opacity: 0, force3D: true });
      gsap.set(bentoHeaderRef.current, { opacity: 0, y: 24, force3D: true });
      gsap.set(bentoGridWrapRef.current, { scale: 1, y: 0, force3D: true });
      gsap.set(thoughtFieldRef.current, { opacity: 0, force3D: true });

      // Ghost Bento cards hidden initially
      gsap.set('.magic-bento-card', { opacity: 0, force3D: true });
      gsap.set('.magic-bento-card__title', { opacity: 0, force3D: true });
      gsap.set('.magic-bento-card__header, .magic-bento-card__description', { opacity: 0, force3D: true });

      // All 30 thoughts (knowledge + random) start at center collapse point
      KNOWLEDGE_ITEMS.forEach((k) => {
        const wrap = fallingThoughtWrapperRefs.current[k.id];
        if (wrap) {
          gsap.set(wrap, {
            x: 0,
            y: 0,
            scale: 0.1,
            rotation: 0,
            opacity: 0,
            force3D: true,
          });
        }
      });

      // Random thoughts start at center collapse point
      RANDOM_THOUGHTS.forEach((r) => {
        const wrap = randomThoughtWrapperRefs.current[r.id];
        if (wrap) {
          gsap.set(wrap, {
            x: 0,
            y: 0,
            scale: 0.1,
            rotation: 0,
            opacity: 0,
            force3D: true,
          });
        }
      });

      // Initialize all regular neural thoughts across all 360 quadrants
      NEURAL_THOUGHTS.forEach((t) => {
        const el = thoughtRefs.current[t.id];
        if (el) {
          gsap.set(el, {
            x: t.from.x,
            y: t.from.y,
            z: t.from.z,
            scale: t.from.scale,
            rotation: t.from.rot,
            opacity: 0,
            force3D: true,
          });
        }
      });

      /* ─────────────────────────────────────────────────────────────
         MASTER CONTINUOUS TIMELINE (0.00 to 100.0)
         Synchronized as ONE continuous camera movement:
         0.00–0.15 : CURRENTLY COOKING & brain approach
         0.15–0.54 : Living biological neural world & 4 depth planes
         0.54–0.64 : Warning messages escalation & brain collapse
         0.64–0.77 : Black thought void with organic undulating thoughts
         0.77–0.915: Staggered falling thoughts cascade into card slots
         0.91–0.94 : Tactile impact thud & handoff
         0.94–100.0: MagicBento settled open and steady
      ───────────────────────────────────────────────────────────── */

      // ── 0.00 -> 0.06: CURRENTLY COOKING steam rising & particles
      tl.to(steamWrapRef.current, {
        opacity: 0.72,
        scale: 1.25,
        y: -45,
        duration: 6.0,
        ease: 'power1.out',
      }, 0);

      tl.to(cookingParticlesRef.current, {
        opacity: 0.85,
        y: -50,
        duration: 6.0,
        ease: 'none',
      }, 0);

      // ── 0.05 -> 0.10: CURRENTLY COOKING moves into depth and fades
      tl.to(cookingDepthRef.current, {
        scale: 0.22,
        y: -15,
        duration: 5.0,
        ease: 'power1.inOut',
      }, 5.0);

      tl.to(cookingDepthRef.current, {
        opacity: 0,
        duration: 3.5,
        ease: 'power1.in',
      }, 6.5);

      // ── 0.07 -> 0.14: Authentic Brain Artwork appears at comfortable size
      tl.to(brainDepthRef.current, {
        opacity: 1,
        duration: 4.5,
        ease: 'power1.out',
      }, 7.0);

      tl.to(atmosphereRef.current, {
        opacity: 0.5,
        scale: 1.15,
        duration: 8.0,
        ease: 'none',
      }, 7.0);

      // ── 0.075 -> 0.15: Editorial warning messages
      // 1. "you are about to enter my brain."
      tl.to(enterBrainRef.current, { opacity: 1, y: 0, scale: 1.0, duration: 0.5, ease: 'power1.out' }, 7.5);
      tl.to(enterBrainRef.current, { opacity: 0, y: -8, scale: 0.99, duration: 0.5, ease: 'power1.in' }, 8.8);

      // 2. "are you sure?"
      tl.to(sureRef.current, { opacity: 1, y: 0, scale: 1.0, duration: 0.5, ease: 'power1.out' }, 9.0);
      tl.to(sureRef.current, { opacity: 0, y: -8, scale: 0.99, duration: 0.5, ease: 'power1.in' }, 10.3);

      // 3. "like... really sure?"
      tl.to(reallySureRef.current, { opacity: 1, y: 0, scale: 1.0, duration: 0.5, ease: 'power1.out' }, 10.5);
      tl.to(reallySureRef.current, { opacity: 0, y: -8, scale: 0.99, duration: 0.5, ease: 'power1.in' }, 11.8);

      // 4. "there might be bugs."
      tl.to(mightBeBugsRef.current, { opacity: 1, y: 0, scale: 1.0, duration: 0.5, ease: 'power1.out' }, 12.0);
      tl.to(mightBeBugsRef.current, { opacity: 0, y: -8, scale: 0.99, duration: 0.5, ease: 'power1.in' }, 13.3);

      // 5. "okay. we're going in."
      tl.to(goingInRef.current, { opacity: 1, y: 0, scale: 1.0, duration: 0.5, ease: 'power1.out' }, 13.5);
      tl.to(goingInRef.current, { opacity: 0, y: -8, scale: 1.01, duration: 0.5, ease: 'power1.in' }, 14.8);

      // ── 0.08 -> 0.15: Camera moves toward brain (scale 0.85 -> 1.8)
      tl.to(brainDepthRef.current, {
        scale: 1.8,
        duration: 7.0,
        ease: 'power1.inOut',
      }, 8.0);

      // ── 0.14 -> 0.18: ENTERING THE BRAIN — CAMERA PENETRATES THE SURFACE
      tl.to(brainDepthRef.current, {
        scale: 5.5,
        opacity: 0,
        duration: 3.5,
        ease: 'power2.in',
      }, 14.0);

      // Microscopic Living Biological Neural Network World emerges!
      tl.to(neuralWorldRef.current, {
        opacity: 1,
        duration: 3.0,
        ease: 'power2.out',
      }, 15.0);

      // ── 0.16 -> 0.22: "I AM INSIDE." MOMENT
      tl.to(insideRef.current, {
        opacity: 0.96,
        scale: 1.0,
        y: 0,
        z: 0,
        duration: 1.8,
        ease: 'power2.out',
      }, 16.0);

      tl.to(insideRef.current, {
        opacity: 0,
        scale: 1.35,
        y: -45,
        z: 220,
        duration: 3.5,
        ease: 'power1.in',
      }, 18.2);

      // ── 0.16 -> 0.54: CAMERA TRAVELS FORWARD THROUGH THE NEURAL NETWORK
      // Continuous camera forward flight with layered depth parallax
      tl.to(cameraRigRef.current, {
        z: 500,
        duration: 38.0,
        ease: 'none',
      }, 16.0);

      tl.to(neuralFarRef.current, {
        scale: 1.45,
        z: 70,
        duration: 38.0,
        ease: 'none',
      }, 16.0);

      tl.to(neuralMidRef.current, {
        scale: 2.6,
        z: 240,
        duration: 38.0,
        ease: 'none',
      }, 16.0);

      tl.to(neuralForeRef.current, {
        scale: 5.2,
        z: 560,
        duration: 38.0,
        ease: 'none',
      }, 16.0);

      tl.to(neuralMicroRef.current, {
        scale: 6.0,
        z: 720,
        duration: 38.0,
        ease: 'none',
      }, 16.0);

      // ── 0.18 -> 0.46: BIOLOGICAL ELECTRICAL SIGNALS TRAVELING THROUGH AXONS ──
      // Signal 1 (18.0 -> 22.0)
      tl.fromTo(sig1Ref.current,
        { x: 260, y: 310, opacity: 0, scale: 0.4 },
        { x: 470, y: 228, opacity: 1, scale: 1.25, duration: 4.0, ease: 'none' },
        18.0
      );
      tl.to(syn1Ref.current, { fill: '#FFF8EB', scale: 1.8, duration: 0.25, yoyo: true, repeat: 1, ease: 'power2.out' }, 21.8);
      tl.to(soma2Ref.current, { fill: '#FFFBF2', scale: 1.4, duration: 0.4, yoyo: true, repeat: 1, ease: 'power2.out' }, 22.0);

      // Signal 2 (22.0 -> 26.0)
      tl.fromTo(sig2Ref.current,
        { x: 480, y: 220, opacity: 0, scale: 0.4 },
        { x: 666, y: 308, opacity: 1, scale: 1.25, duration: 4.0, ease: 'none' },
        22.0
      );
      tl.to(syn2Ref.current, { fill: '#FFF8EB', scale: 2.0, duration: 0.25, yoyo: true, repeat: 1, ease: 'power2.out' }, 25.8);
      tl.to(soma3Ref.current, { fill: '#FFFFFF', scale: 1.5, duration: 0.5, yoyo: true, repeat: 1, ease: 'power2.out' }, 26.0);

      // Signal 3 & 4 (26.0 -> 31.0)
      tl.fromTo(sig3Ref.current,
        { x: 680, y: 320, opacity: 0, scale: 0.4 },
        { x: 532, y: 506, opacity: 1, scale: 1.25, duration: 4.0, ease: 'none' },
        26.0
      );
      tl.to(syn3Ref.current, { fill: '#FFF8EB', scale: 1.8, duration: 0.25, yoyo: true, repeat: 1 }, 29.8);
      tl.to(soma5Ref.current, { fill: '#FFECC8', scale: 1.4, duration: 0.4, yoyo: true, repeat: 1 }, 30.0);

      tl.fromTo(sig4Ref.current,
        { x: 680, y: 320, opacity: 0, scale: 0.4 },
        { x: 848, y: 192, opacity: 1, scale: 1.25, duration: 4.0, ease: 'none' },
        27.5
      );
      tl.to(syn4Ref.current, { fill: '#FFF8EB', scale: 1.8, duration: 0.25, yoyo: true, repeat: 1 }, 31.2);
      tl.to(soma4Ref.current, { fill: '#FFFFFF', scale: 1.45, duration: 0.4, yoyo: true, repeat: 1 }, 31.5);

      // Signal 5 & 6 (31.0 -> 36.5)
      tl.fromTo(sig5Ref.current,
        { x: 520, y: 520, opacity: 0, scale: 0.4 },
        { x: 335, y: 570, opacity: 1, scale: 1.25, duration: 4.0, ease: 'none' },
        31.0
      );
      tl.to(syn5Ref.current, { fill: '#FFF8EB', scale: 1.8, duration: 0.25, yoyo: true, repeat: 1 }, 34.8);
      tl.to(soma6Ref.current, { fill: '#FFE5B4', scale: 1.4, duration: 0.4, yoyo: true, repeat: 1 }, 35.0);

      tl.fromTo(sig6Ref.current,
        { x: 860, y: 180, opacity: 0, scale: 0.4 },
        { x: 960, y: 368, opacity: 1, scale: 1.25, duration: 4.0, ease: 'none' },
        32.5
      );
      tl.to(syn6Ref.current, { fill: '#FFF8EB', scale: 1.8, duration: 0.25, yoyo: true, repeat: 1 }, 36.2);
      tl.to(soma8Ref.current, { fill: '#FFE5B4', scale: 1.4, duration: 0.4, yoyo: true, repeat: 1 }, 36.5);

      // Signal 7 & 8 (36.0 -> 42.0)
      tl.fromTo(sig7Ref.current,
        { x: 320, y: 580, opacity: 0, scale: 0.4 },
        { x: 120, y: 420, opacity: 1, scale: 1.25, duration: 4.0, ease: 'none' },
        36.0
      );
      tl.to(soma9Ref.current, { fill: '#FFF8EB', scale: 1.4, duration: 0.4, yoyo: true, repeat: 1 }, 39.8);

      tl.fromTo(sig8Ref.current,
        { x: 480, y: 220, opacity: 0, scale: 0.4 },
        { x: 620, y: 140, opacity: 1, scale: 1.25, duration: 4.0, ease: 'none' },
        38.0
      );
      tl.to(soma10Ref.current, { fill: '#FFFFFF', scale: 1.4, duration: 0.4, yoyo: true, repeat: 1 }, 41.8);

      // Synaptic sparks across neuropil web
      tl.to('.synapse-spark', {
        opacity: 0.9,
        duration: 8.0,
        ease: 'power2.in',
      }, 38.0);

      // ── 0.16 -> 0.46: INDIVIDUAL THOUGHT TRAJECTORIES THROUGH 3D DEPTH ──
      NEURAL_THOUGHTS.forEach((t) => {
        const el = thoughtRefs.current[t.id];
        if (!el) return;

        // Proportional linear mapping to neural flight interval (16.0 -> 46.0)
        const mapT = (val) => 16.0 + (val - 39.0) * (30.0 / 49.0);
        const tIn = mapT(t.in);
        const tPeak = mapT(t.peak);
        const tOut = mapT(t.out);

        const fadeInDur = Math.max(0.4, (tPeak - tIn) * 0.8);
        const fadeOutStart = tPeak + (tOut - tPeak) * 0.35;
        const fadeOutDur = Math.max(0.4, tOut - fadeOutStart);
        const totalDur = tOut - tIn;

        tl.to(el, {
          x: t.to.x,
          y: t.to.y,
          z: t.to.z,
          scale: t.to.scale,
          rotation: t.to.rot,
          duration: totalDur,
          ease: 'none',
        }, tIn);

        tl.to(el, {
          opacity: 0.95,
          duration: fadeInDur,
          ease: 'power1.out',
        }, tIn);

        tl.to(el, {
          opacity: 0,
          duration: fadeOutDur,
          ease: 'power1.in',
        }, fadeOutStart);
      });

      // ── 0.460 -> 0.564: LAYER 7: BOTTOM WARNING SYSTEM (Gradual Escalation) ──
      tl.to(warningRef.current, { opacity: 1, y: 0, duration: 0.6, ease: 'power1.out' }, 46.0);
      tl.to(w1Ref.current, { opacity: 1, y: 0, duration: 0.5, ease: 'power1.out' }, 46.0);
      tl.to(w1Ref.current, { opacity: 0, y: -6, duration: 0.4, ease: 'power1.in' }, 47.4);

      tl.to(w2Ref.current, { opacity: 1, y: 0, duration: 0.5, ease: 'power1.out' }, 47.6);
      tl.to(w2Ref.current, { opacity: 0, y: -6, duration: 0.4, ease: 'power1.in' }, 49.0);

      tl.to(w3Ref.current, { opacity: 1, y: 0, duration: 0.5, ease: 'power1.out' }, 49.2);
      tl.to(w3Ref.current, { opacity: 0, y: -6, duration: 0.4, ease: 'power1.in' }, 50.6);

      tl.to(w4Ref.current, { opacity: 1, y: 0, duration: 0.5, ease: 'power1.out' }, 50.8);
      tl.to(w4Ref.current, { opacity: 0, y: -6, duration: 0.4, ease: 'power1.in' }, 52.2);

      tl.to(w5Ref.current, { opacity: 1, y: 0, duration: 0.5, ease: 'power1.out' }, 52.4);
      tl.to(w5Ref.current, { opacity: 0, y: -6, duration: 0.4, ease: 'power1.in' }, 53.8);

      tl.to(w6Ref.current, { opacity: 1, y: 0, duration: 0.5, ease: 'power1.out' }, 54.0);
      tl.to(w6Ref.current, { opacity: 0, y: -6, duration: 0.4, ease: 'power1.in' }, 55.2);

      tl.to(w7Ref.current, { opacity: 1, y: 0, duration: 0.4, ease: 'power1.out' }, 55.4);
      tl.to(w7Ref.current, { opacity: 0, y: -6, duration: 0.4, ease: 'power2.in' }, 56.4);
      tl.to(warningRef.current, { opacity: 0, duration: 0.4, ease: 'power2.in' }, 56.4);

      // ── 0.565 -> 0.568: VERY SHORT BLACK SCREEN FLASH ──
      tl.set(blackFlashRef.current, { opacity: 1 }, 56.5);
      tl.set(blackFlashRef.current, { opacity: 0 }, 56.8);

      // ── 0.568 -> 0.588: MEMORY COLLAPSE INTO BLACK ──
      tl.to('.neural-thought', {
        x: 0,
        y: 0,
        z: 0,
        scale: 0.05,
        opacity: 0,
        duration: 2.0,
        ease: 'power3.in',
      }, 56.8);

      tl.to([neuralFarRef.current, neuralMidRef.current, neuralForeRef.current, neuralMicroRef.current], {
        scale: 0.5,
        opacity: 0,
        duration: 2.0,
        ease: 'power3.in',
      }, 56.8);

      tl.to(journeyWrapperRef.current, {
        opacity: 0,
        duration: 2.0,
        ease: 'power2.in',
      }, 56.8);

      // ── 0.588 -> 0.640: BLACK THOUGHT VOID & FULL ORGANIC THOUGHT CLOUD ──
      // SIMULTANEOUSLY: Bento layer and thought field emerge from the collapse
      tl.set(bentoSectionRef.current, { opacity: 1 }, 58.8);
      tl.fromTo(thoughtFieldRef.current,
        { opacity: 0 },
        { opacity: 1, duration: 0.8, ease: 'power1.out' },
        58.8
      );

      // The 6 Knowledge Thoughts burst outward from collapse into their natural cloud positions
      KNOWLEDGE_ITEMS.forEach((k) => {
        const wrap = fallingThoughtWrapperRefs.current[k.id];
        if (wrap) {
          tl.fromTo(wrap,
            { x: 0, y: 0, scale: 0.1, rotation: 0, opacity: 0 },
            { x: k.x, y: k.y, scale: 1.0, rotation: k.rot, opacity: 0.82, duration: 2.0, ease: 'power2.out' },
            58.8
          );
        }
      });

      // The 24 Random Subconscious Thoughts burst outward across the screen
      RANDOM_THOUGHTS.forEach((r) => {
        const wrap = randomThoughtWrapperRefs.current[r.id];
        if (wrap) {
          tl.fromTo(wrap,
            { x: 0, y: 0, scale: 0.1, rotation: 0, opacity: 0 },
            { x: r.x, y: r.y, scale: r.scale, rotation: r.rot, opacity: 0.75, duration: 2.0, ease: 'power2.out' },
            58.8
          );
        }
      });

      // The entire organic thought cloud is visible and floating across the screen
      tl.to({}, { duration: 3.2 }, 60.8);

      // ── 0.620: GHOST CARD SHELLS EMERGE IN THE BENTO GRID ──
      tl.fromTo('.magic-bento-card',
        { opacity: 0, scale: 0.95 },
        { opacity: 0.25, scale: 0.98, duration: 3.0, ease: 'power1.out' },
        62.0
      );

      // ── PHASE 5: OTHER THOUGHTS GRADUALLY DRIFT TOWARD DARKNESS ──
      // While thoughts are extracted one by one, random thoughts dim gracefully
      tl.to('.random-thought-wrapper', { opacity: 0.45, duration: 6.0, ease: 'power1.inOut' }, 64.0);
      tl.to('.random-thought-wrapper', { opacity: 0.18, duration: 8.0, ease: 'power1.inOut' }, 72.0);
      tl.to('.random-thought-wrapper', { opacity: 0.0, duration: 4.0, ease: 'power1.in' }, 82.0);

      // ── 0.640 -> 0.936: CINEMATIC EXTRACTION OF THE 6 THOUGHTS FROM THE CLOUD ──
      const computeTargets = () => {
        const fallbackTargets = {
          'photography': { x: -260, y: -45 },
          'videography': { x: 270, y: -45 },
          'video-editing': { x: -280, y: 75 },
          'c': { x: -45, y: 75 },
          'java': { x: 235, y: 75 },
          'vibe-coding': { x: 0, y: 200 },
        };
        const stageEl = stageRef.current;
        if (!stageEl) return fallbackTargets;

        const stageRect = stageEl.getBoundingClientRect();
        const centerX = stageRect.left + stageRect.width / 2;
        const centerY = stageRect.top + stageRect.height / 2;

        const targets = {};
        KNOWLEDGE_ITEMS.forEach((k) => {
          const cardTitle = stageEl.querySelector(`.magic-bento-card__title[data-card-id="${k.id}"]`) ||
                            stageEl.querySelector(`.magic-bento-card[data-card-id="${k.id}"] .magic-bento-card__title`) ||
                            stageEl.querySelector(`[data-card-id="${k.id}"] .magic-bento-card__title`);
          if (cardTitle) {
            const r = cardTitle.getBoundingClientRect();
            if (r.width > 0 && r.height > 0) {
              targets[k.id] = {
                x: (r.left + r.width / 2) - centerX,
                y: (r.top + r.height / 2) - centerY,
              };
              return;
            }
          }
          targets[k.id] = fallbackTargets[k.id] || { x: 0, y: 0 };
        });

        return targets;
      };

      const targets = computeTargets();

      // 6 Staggered Thought Extractions — Each selected from its natural position in the cloud!
      const THOUGHT_CONFIGS = [
        { id: 'photography',   t0: 64.0 },
        { id: 'videography',   t0: 69.0 },
        { id: 'video-editing', t0: 74.0 },
        { id: 'c',             t0: 79.0 },
        { id: 'java',          t0: 84.0 },
        { id: 'vibe-coding',   t0: 89.0 },
      ];

      const stageEl = stageRef.current;

      THOUGHT_CONFIGS.forEach(({ id, t0 }) => {
        const k = KNOWLEDGE_ITEMS.find(item => item.id === id);
        const wrap = fallingThoughtWrapperRefs.current[id];
        const inner = fallingThoughtInnerRefs.current[id];
        const trail = fallingTrailRefs.current[id];
        const target = targets[id] || { x: 0, y: 0 };
        const cardTitle = stageEl
          ? (stageEl.querySelector(`.magic-bento-card__title[data-card-id="${id}"]`) ||
             stageEl.querySelector(`.magic-bento-card[data-card-id="${id}"] .magic-bento-card__title`) ||
             stageEl.querySelector(`[data-card-id="${id}"] .magic-bento-card__title`))
          : null;
        const cardEl = stageEl
          ? (stageEl.querySelector(`.magic-bento-card[data-card-id="${id}"]`) ||
             (cardTitle ? cardTitle.closest('.magic-bento-card') : null))
          : null;

        if (!wrap || !k) return;

        // STARTING POINT IS EXACTLY WHERE IT WAS FLOATING IN THE CLOUD!
        const startX = k.x;
        const startY = k.y;
        const totalDistY = target.y - startY;
        const midY = Math.round(startY + totalDistY * 0.70);
        const midX = Math.round(startX + (target.x - startX) * 0.70);

        // ── PHASE 2: SELECT A REAL THOUGHT (t0 -> t0 + 0.8) ──
        // The thought is selected from the existing cloud.
        // It brightens, becomes sharper, and gains a focused aura at its exact cloud position.
        tl.to(wrap, {
          scale: 1.08,
          opacity: 1.0,
          duration: 0.4,
          ease: 'power2.out',
        }, t0);

        if (inner) {
          tl.to(inner, {
            color: '#FFFFFF',
            textShadow: '0 0 20px rgba(255, 245, 230, 0.95), 0 2px 10px rgba(0, 0, 0, 0.95)',
            duration: 0.4,
            ease: 'power2.out',
          }, t0);
        }

        // Slight zero-g anticipation hold
        tl.to(wrap, {
          y: startY - 4,
          duration: 0.4,
          ease: 'sine.inOut',
        }, t0 + 0.4);

        // ── PHASE 3 & 4: NATURAL FALL FROM ITS CLOUD POSITION (t0 + 0.8 -> t0 + 3.4) ──
        // Begins moving downward slow at first, glides steadily across the black void
        tl.to(wrap, {
          x: midX,
          y: midY,
          rotation: k.rot * 0.25,
          duration: 2.6,
          ease: 'power1.in', // slow start -> long steady descent through middle
        }, t0 + 0.8);

        // Lightweight visual trail stretches behind the falling thought
        if (trail) {
          tl.to(trail, {
            opacity: 0.85,
            scaleY: 1.0,
            duration: 1.2,
            ease: 'power1.out',
          }, t0 + 1.2);
          tl.to(trail, {
            opacity: 1.0,
            scaleY: 1.6,
            duration: 1.0,
            ease: 'power2.in',
          }, t0 + 2.4);
        }

        // ── LATE ACCELERATION (t0 + 3.4 -> t0 + 4.5) ──
        // Final ~25% of descent accelerates into the card
        tl.to(wrap, {
          x: target.x,
          y: target.y,
          rotation: 0,
          scale: 1.0,
          duration: 1.1,
          ease: 'power2.in', // slight acceleration into crash!
        }, t0 + 3.4);

        // ── PHASE 5: IMPACT / CRASH & HANDOFF (at t0 + 4.5) ──
        const impactTime = t0 + 4.5;

        // Trail vanishes immediately on impact
        if (trail) {
          tl.to(trail, { opacity: 0, scaleY: 0.2, duration: 0.15, ease: 'power1.out' }, impactTime);
        }

        // Falling thought hands off cleanly to native card title
        tl.to(wrap, { opacity: 0, visibility: 'hidden', duration: 0.2, ease: 'power1.out' }, impactTime);

        if (cardTitle) {
          tl.to(cardTitle, { opacity: 1, visibility: 'visible', duration: 0.35, ease: 'power2.out' }, impactTime);
        }

        if (cardEl) {
          // Card micro scale punch + border glow
          tl.to(cardEl, { opacity: 1.0, visibility: 'visible', duration: 0.35 }, impactTime);
          tl.fromTo(cardEl,
            { scale: 1.05 },
            { scale: 1.0, duration: 0.45, ease: 'back.out(2)' },
            impactTime
          );
        }
      });

      // ── 93.6 -> 100.0: INSTANT BENTO REVEAL & BRIEF IMPACT SETTLING ──
      // Tactile settling impact thud of the entire Bento grid (extremely brief scale punch)
      tl.fromTo(bentoGridWrapRef.current,
        { scale: 0.98, y: -4 },
        { scale: 1.0, y: 0, duration: 0.4, ease: 'back.out(2)' },
        93.6
      );

      // All cards ensure 100% immediate visibility at moment of impact
      tl.to('.magic-bento-card', {
        opacity: 1,
        visibility: 'visible',
        duration: 0.15,
        ease: 'power1.out',
      }, 93.6);

      // ALL card titles unconditionally become fully visible & readable immediately
      tl.to('.magic-bento-card__title', {
        opacity: 1,
        visibility: 'visible',
        duration: 0.2,
        ease: 'power1.out',
      }, 93.6);

      // All card details (headers, descriptions) immediately visible & readable
      tl.to('.magic-bento-card__header, .magic-bento-card__description', {
        opacity: 1,
        visibility: 'visible',
        duration: 0.2,
        ease: 'power1.out',
      }, 93.6);

      // Section title ("THINGS I SOMEHOW KNOW") immediately settles crisply above grid
      tl.fromTo(bentoHeaderRef.current,
        { opacity: 0, y: 12 },
        { opacity: 1, y: 0, duration: 0.35, ease: 'power2.out' },
        93.6
      );

      // Fade out and hide the floating thought field container completely so it never covers the Bento
      tl.to(thoughtFieldRef.current, {
        opacity: 0,
        visibility: 'hidden',
        duration: 0.3,
        ease: 'power1.out',
      }, 93.6);

      // Hold Bento stage open, clearly visible and readable through 100.0
      tl.to({}, { duration: 6.0 }, 94.0);

    }, container);

    return () => {
      ctx.revert();
    };
  }, []);

  return (
    <section ref={containerRef} className="brain-entry-section" aria-label="Currently Cooking and Living Neural Journey">
      <div ref={stageRef} className="brain-entry-stage">

        {/* ── THE MASTER CAMERA / JOURNEY WRAPPER ── */}
        <div ref={journeyWrapperRef} className="brain-journey">

          {/* ── ATMOSPHERIC VOID BACKGROUND ── */}
          <div ref={atmosphereRef} className="brain-journey-atmosphere" aria-hidden="true" />

          {/* ── MASTER CAMERA RIG ── */}
          <div ref={cameraRigRef} className="brain-camera-rig">

            {/* ── LAYER 1: CURRENTLY COOKING IN DEPTH SPACE ── */}
            <div ref={cookingDepthRef} className="currently-cooking-depth" aria-label="Currently Cooking">
              <div className="cooking-title-wrap">
                <h2 className="cooking-word-currently">CURRENTLY</h2>
                <div className="cooking-word-cooking-container">
                  <h2 className="cooking-word-cooking">COOKING</h2>

                  {/* Soft rising steam plumes */}
                  <div ref={steamWrapRef} className="cooking-steam-container" aria-hidden="true">
                    <div className="steam-plume plume-1" />
                    <div className="steam-plume plume-2" />
                    <div className="steam-plume plume-3" />
                    <div className="steam-plume plume-4" />
                  </div>

                  {/* Tiny floating particles */}
                  <div ref={cookingParticlesRef} className="cooking-particles" aria-hidden="true">
                    <span className="particle p1" />
                    <span className="particle p2" />
                    <span className="particle p3" />
                    <span className="particle p4" />
                    <span className="particle p5" />
                    <span className="particle p6" />
                  </div>
                </div>
              </div>
            </div>

            {/* ── LAYER 2: THE AUTHENTIC HUMAN BRAIN CENTERPIECE ── */}
            <div ref={brainDepthRef} className="brain-depth" aria-hidden="true">
              <div className="brain-inner-wrap">
                <BrainArtwork />
              </div>
            </div>

            {/* ── LAYER 3: THE LIVING BIOLOGICAL NEURAL NETWORK ENVIRONMENT (4 Depth Tiers) ── */}
            <div ref={neuralWorldRef} className="neural-network-world" aria-hidden="true">

              {/* 3A: Far Neuropil Mesh & Distant Parenchymal Tissue Contours */}
              <svg ref={neuralFarRef} className="neural-plane neural-plane-far" viewBox="0 0 1200 800" fill="none">
                {/* Subtle organic brain parenchymal tissue contours in distant background */}
                <path d="M -80 80 C 140 20, 260 140, 480 80 C 700 20, 880 120, 1100 60 C 1220 30, 1280 80, 1340 50 L 1340 350 C 1240 380, 1080 320, 880 380 C 680 440, 480 360, 280 420 C 120 460, -40 400, -80 440 Z" fill="#2E1744" fillOpacity="0.22" />
                <path d="M -80 420 C 140 360, 320 460, 520 400 C 720 340, 920 440, 1120 380 C 1240 350, 1300 400, 1340 380 L 1340 850 L -80 850 Z" fill="#241038" fillOpacity="0.25" />

                {/* Dense interlaced neuropil capillary highways */}
                <path d="M -50 120 C 120 180, 260 90, 420 150 C 580 210, 720 130, 920 170 C 1080 200, 1180 140, 1260 180" stroke="#483262" strokeWidth="0.8" strokeOpacity="0.35" strokeDasharray="3 4" />
                <path d="M -40 320 C 140 280, 280 340, 440 310 C 600 280, 740 330, 910 290 C 1050 260, 1160 310, 1250 280" stroke="#483262" strokeWidth="0.8" strokeOpacity="0.32" />
                <path d="M -30 520 C 150 480, 310 560, 470 510 C 630 460, 770 530, 930 490 C 1070 460, 1170 510, 1260 480" stroke="#3F2B56" strokeWidth="0.8" strokeOpacity="0.3" strokeDasharray="4 4" />
                <path d="M -50 710 C 130 670, 290 730, 460 690 C 630 650, 780 720, 950 670 C 1090 630, 1190 680, 1270 650" stroke="#38254C" strokeWidth="0.8" strokeOpacity="0.28" />

                {/* Vertical / diagonal cross-mesh branches */}
                <path d="M 180 -40 C 220 140, 160 290, 240 440 C 310 570, 260 680, 300 840" stroke="#442E5C" strokeWidth="0.75" strokeOpacity="0.3" />
                <path d="M 440 -30 C 410 130, 480 270, 430 420 C 390 560, 460 690, 420 830" stroke="#442E5C" strokeWidth="0.75" strokeOpacity="0.3" />
                <path d="M 720 -40 C 760 120, 690 280, 750 430 C 800 560, 730 690, 770 840" stroke="#442E5C" strokeWidth="0.75" strokeOpacity="0.3" />
                <path d="M 980 -30 C 950 140, 1020 280, 960 430 C 910 570, 990 690, 940 840" stroke="#442E5C" strokeWidth="0.75" strokeOpacity="0.28" />

                {/* Intricate dendritic micro-tufts in background */}
                <path d="M 160 140 C 140 110, 120 125, 95 105 M 140 110 C 130 90, 145 75, 135 60 M 160 140 C 190 125, 210 135, 235 115" stroke="#543A72" strokeWidth="0.7" strokeOpacity="0.38" />
                <path d="M 380 210 C 360 180, 340 195, 315 175 M 360 180 C 350 160, 365 145, 355 130 M 380 210 C 410 195, 430 205, 455 185" stroke="#543A72" strokeWidth="0.7" strokeOpacity="0.38" />
                <path d="M 640 160 C 620 130, 600 145, 575 125 M 620 130 C 610 110, 625 95, 615 80 M 640 160 C 670 145, 690 155, 715 135" stroke="#543A72" strokeWidth="0.7" strokeOpacity="0.38" />
                <path d="M 880 220 C 860 190, 840 205, 815 185 M 860 190 C 850 170, 865 155, 855 140 M 880 220 C 910 205, 930 215, 955 195" stroke="#543A72" strokeWidth="0.7" strokeOpacity="0.38" />
                <path d="M 240 640 C 220 610, 200 625, 175 605 M 220 610 C 210 590, 225 575, 215 560 M 240 640 C 270 625, 290 635, 315 615" stroke="#4C3468" strokeWidth="0.7" strokeOpacity="0.35" />
                <path d="M 820 630 C 800 600, 780 615, 755 595 M 800 600 C 790 580, 805 565, 795 550 M 820 630 C 850 615, 870 625, 895 605" stroke="#4C3468" strokeWidth="0.7" strokeOpacity="0.35" />

                {/* Distant small multipolar neuron bodies */}
                <g className="far-neuron" transform="translate(160, 140)">
                  <path d="M -4 -2 Q -6 -6 -2 -6 Q 3 -7 5 -3 Q 6 2 3 4 Q -1 5 -4 -2 Z" fill="#6A4E88" opacity="0.65" />
                </g>
                <g className="far-neuron" transform="translate(380, 210)">
                  <path d="M -4 -2 Q -6 -6 -2 -6 Q 3 -7 5 -3 Q 6 2 3 4 Q -1 5 -4 -2 Z" fill="#6A4E88" opacity="0.65" />
                </g>
                <g className="far-neuron" transform="translate(640, 160)">
                  <path d="M -4 -2 Q -6 -6 -2 -6 Q 3 -7 5 -3 Q 6 2 3 4 Q -1 5 -4 -2 Z" fill="#6A4E88" opacity="0.65" />
                </g>
                <g className="far-neuron" transform="translate(880, 220)">
                  <path d="M -4 -2 Q -6 -6 -2 -6 Q 3 -7 5 -3 Q 6 2 3 4 Q -1 5 -4 -2 Z" fill="#6A4E88" opacity="0.65" />
                </g>
                <g className="far-neuron" transform="translate(1060, 180)">
                  <path d="M -4 -2 Q -6 -6 -2 -6 Q 3 -7 5 -3 Q 6 2 3 4 Q -1 5 -4 -2 Z" fill="#6A4E88" opacity="0.65" />
                </g>
                <g className="far-neuron" transform="translate(140, 520)">
                  <path d="M -4 -2 Q -6 -6 -2 -6 Q 3 -7 5 -3 Q 6 2 3 4 Q -1 5 -4 -2 Z" fill="#6A4E88" opacity="0.6" />
                </g>
                <g className="far-neuron" transform="translate(420, 610)">
                  <path d="M -4 -2 Q -6 -6 -2 -6 Q 3 -7 5 -3 Q 6 2 3 4 Q -1 5 -4 -2 Z" fill="#6A4E88" opacity="0.6" />
                </g>
                <g className="far-neuron" transform="translate(760, 640)">
                  <path d="M -4 -2 Q -6 -6 -2 -6 Q 3 -7 5 -3 Q 6 2 3 4 Q -1 5 -4 -2 Z" fill="#6A4E88" opacity="0.6" />
                </g>
                <g className="far-neuron" transform="translate(1040, 560)">
                  <path d="M -4 -2 Q -6 -6 -2 -6 Q 3 -7 5 -3 Q 6 2 3 4 Q -1 5 -4 -2 Z" fill="#6A4E88" opacity="0.6" />
                </g>
              </svg>

              {/* 3B: Midground Biological Neural Network (Primary multipolar neurons, arborized dendrites, axons, synaptic boutons) */}
              <svg ref={neuralMidRef} className="neural-plane neural-plane-mid" viewBox="0 0 1200 800" fill="none">
                <defs>
                  <radialGradient id="somaHaloGrad" cx="50%" cy="50%" r="50%">
                    <stop offset="0%" stopColor="#DEC8F5" stopOpacity="0.75" />
                    <stop offset="45%" stopColor="#7E5F9E" stopOpacity="0.35" />
                    <stop offset="100%" stopColor="#35204C" stopOpacity="0" />
                  </radialGradient>
                </defs>

                {/* ── LONG ORGANIC AXON HIGHWAYS ── */}
                <path d="M 268 308 C 320 280, 380 260, 440 240 C 452 236, 462 232, 470 228" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.45" />
                <path d="M 488 224 C 540 245, 600 275, 645 295 C 655 300, 660 304, 666 308" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.45" />
                <path d="M 676 326 C 640 380, 590 440, 555 485 C 545 495, 538 502, 532 506" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.45" />
                <path d="M 688 316 C 735 275, 790 230, 830 205 C 838 200, 844 195, 848 192" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.45" />
                <path d="M 512 524 C 460 545, 400 560, 355 568 C 348 569, 340 570, 335 570" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.45" />
                <path d="M 865 188 C 895 240, 930 300, 950 345 C 955 355, 958 362, 960 368" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.45" />
                <path d="M 314 576 C 260 530, 190 480, 140 440 C 132 432, 125 425, 120 420" stroke="#564073" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.4" />
                <path d="M 486 214 C 520 190, 565 165, 605 148 C 612 144, 616 142, 620 140" stroke="#564073" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.4" />

                {/* Ambient Axons crossing field */}
                <path d="M -40 280 C 120 340, 280 460, 440 500 C 600 540, 780 480, 960 520 C 1080 550, 1180 620, 1260 660" stroke="#4A3466" strokeWidth="1.1" strokeLinecap="round" strokeOpacity="0.32" />
                <path d="M 700 -30 C 720 80, 760 180, 800 280 C 830 380, 810 480, 840 580 C 860 660, 890 740, 920 840" stroke="#4A3466" strokeWidth="1.1" strokeLinecap="round" strokeOpacity="0.32" />
                <path d="M -30 620 C 80 580, 180 590, 280 610 C 380 630, 480 670, 580 700 C 720 740, 880 720, 1020 760 C 1140 790, 1220 810, 1280 820" stroke="#4A3466" strokeWidth="1.1" strokeLinecap="round" strokeOpacity="0.3" />

                {/* ── ORGANIC BIOLOGICAL NEURONS ── */}
                {/* NEURON 1 */}
                <g id="neuron-1">
                  <path d="M 252 304 C 230 285, 205 270, 175 260 M 205 270 C 190 250, 175 235, 155 225 M 205 270 C 215 245, 230 225, 235 205" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 264 302 C 265 270, 272 240, 280 210 M 272 240 C 290 225, 310 215, 325 195" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 254 316 C 235 335, 215 360, 190 385 M 215 360 C 210 385, 200 410, 185 430" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 266 318 C 275 345, 290 375, 305 405 M 290 375 C 310 395, 330 415, 345 440" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <ellipse cx="260" cy="310" rx="18" ry="15" fill="url(#somaHaloGrad)" className="soma-halo-organic" />
                  <path ref={soma1Ref} d="M 250 306 Q 244 298 252 294 Q 262 288 270 294 Q 278 300 274 310 Q 268 322 258 320 Q 248 318 250 306 Z" fill="#755B92" className="neuron-soma-organic" />
                </g>

                {/* NEURON 2 */}
                <g id="neuron-2">
                  <path d="M 479 212 C 475 160, 468 110, 460 65 M 468 110 C 450 85, 430 70, 410 50 M 468 110 C 485 85, 505 65, 530 45" stroke="#664E87" strokeWidth="1.4" strokeLinecap="round" strokeOpacity="0.55" />
                  <path d="M 472 225 C 450 240, 425 255, 395 265 M 425 255 C 415 275, 400 295, 380 310" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 488 226 C 510 242, 535 258, 565 268 M 535 258 C 550 278, 570 295, 595 305" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <ellipse ref={syn1Ref} cx="470" cy="228" rx="2.5" ry="1.8" fill="#8F73AC" className="synapse-bouton" />
                  <ellipse cx="480" cy="220" rx="19" ry="16" fill="url(#somaHaloGrad)" className="soma-halo-organic" />
                  <path ref={soma2Ref} d="M 478 210 Q 486 210 490 218 Q 494 226 486 230 Q 476 234 472 226 Q 470 216 478 210 Z" fill="#8568A5" className="neuron-soma-organic" />
                </g>

                {/* NEURON 3 */}
                <g id="neuron-3">
                  <path d="M 672 312 C 650 290, 630 265, 605 240 M 630 265 C 620 240, 605 220, 585 200 M 630 265 C 645 240, 665 220, 680 195" stroke="#6F5593" strokeWidth="1.4" strokeLinecap="round" strokeOpacity="0.6" />
                  <path d="M 686 312 C 710 290, 735 268, 765 245 M 735 268 C 750 245, 770 225, 795 205 M 735 268 C 725 240, 715 215, 705 190" stroke="#6F5593" strokeWidth="1.4" strokeLinecap="round" strokeOpacity="0.6" />
                  <path d="M 674 328 C 655 350, 630 375, 600 400 M 630 375 C 625 405, 615 430, 600 455" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 688 326 C 715 350, 745 375, 775 398 M 745 375 C 765 400, 785 425, 810 445" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.5" />
                  <ellipse ref={syn2Ref} cx="666" cy="308" rx="2.8" ry="2.0" fill="#997DC0" className="synapse-bouton" />
                  <ellipse cx="680" cy="320" rx="22" ry="18" fill="url(#somaHaloGrad)" className="soma-halo-organic" />
                  <path ref={soma3Ref} d="M 676 310 Q 688 308 694 316 Q 698 326 690 332 Q 678 336 672 328 Q 668 318 676 310 Z" fill="#8C6EAF" className="neuron-soma-organic" />
                </g>

                {/* NEURON 4 */}
                <g id="neuron-4">
                  <path d="M 854 172 C 835 150, 810 130, 780 110 M 810 130 C 805 105, 795 85, 780 65" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 868 174 C 895 150, 925 130, 960 110 M 925 130 C 945 105, 970 85, 995 70" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 855 188 C 840 210, 820 235, 795 260" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <ellipse ref={syn4Ref} cx="848" cy="192" rx="2.5" ry="1.8" fill="#8F73AC" className="synapse-bouton" />
                  <ellipse cx="860" cy="180" rx="18" ry="15" fill="url(#somaHaloGrad)" className="soma-halo-organic" />
                  <path ref={soma4Ref} d="M 856 172 Q 866 170 872 178 Q 876 186 868 192 Q 858 194 852 186 Q 850 178 856 172 Z" fill="#7B5F9D" className="neuron-soma-organic" />
                </g>

                {/* NEURON 5 */}
                <g id="neuron-5">
                  <path d="M 512 512 C 490 490, 465 470, 435 450 M 465 470 C 450 445, 430 425, 410 405" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 526 512 C 545 490, 570 470, 600 450 M 570 470 C 585 445, 605 425, 630 410" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 524 528 C 535 560, 550 595, 570 630 M 550 595 C 570 618, 595 640, 620 660" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.5" />
                  <ellipse ref={syn3Ref} cx="532" cy="506" rx="2.5" ry="1.8" fill="#8F73AC" className="synapse-bouton" />
                  <ellipse cx="520" cy="520" rx="20" ry="16" fill="url(#somaHaloGrad)" className="soma-halo-organic" />
                  <path ref={soma5Ref} d="M 514 512 Q 526 510 532 518 Q 536 528 528 534 Q 518 536 512 528 Q 508 518 514 512 Z" fill="#7E61A0" className="neuron-soma-organic" />
                </g>

                {/* NEURON 6 */}
                <g id="neuron-6">
                  <path d="M 314 572 C 295 550, 270 530, 240 510" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 326 572 C 345 550, 370 530, 400 510" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 324 588 C 335 618, 350 650, 368 685" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <ellipse ref={syn5Ref} cx="335" cy="570" rx="2.4" ry="1.8" fill="#8F73AC" className="synapse-bouton" />
                  <ellipse cx="320" cy="580" rx="18" ry="15" fill="url(#somaHaloGrad)" className="soma-halo-organic" />
                  <path ref={soma6Ref} d="M 314 574 Q 324 570 330 578 Q 334 586 326 592 Q 316 594 312 586 Q 310 578 314 574 Z" fill="#755B92" className="neuron-soma-organic" />
                </g>

                {/* NEURON 7 */}
                <g id="neuron-7">
                  <path d="M 814 552 C 795 530, 770 510, 740 490" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 826 552 C 845 530, 870 510, 900 495" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 822 568 C 830 598, 845 630, 865 660" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <ellipse cx="820" cy="560" rx="18" ry="15" fill="url(#somaHaloGrad)" className="soma-halo-organic" />
                  <path ref={soma7Ref} d="M 814 554 Q 824 550 830 558 Q 834 566 826 572 Q 816 574 812 566 Q 810 558 814 554 Z" fill="#755B92" className="neuron-soma-organic" />
                </g>

                {/* NEURON 8 */}
                <g id="neuron-8">
                  <path d="M 962 372 C 940 350, 915 330, 885 310" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 976 372 C 1005 350, 1040 330, 1080 310" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 972 388 C 980 418, 995 450, 1015 480" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <ellipse ref={syn6Ref} cx="960" cy="368" rx="2.5" ry="1.8" fill="#8F73AC" className="synapse-bouton" />
                  <ellipse cx="970" cy="380" rx="18" ry="15" fill="url(#somaHaloGrad)" className="soma-halo-organic" />
                  <path ref={soma8Ref} d="M 964 374 Q 974 370 980 378 Q 984 386 976 392 Q 966 394 962 386 Q 960 378 964 374 Z" fill="#755B92" className="neuron-soma-organic" />
                </g>

                {/* NEURON 9 */}
                <g id="neuron-9">
                  <path d="M 112 412 C 90 390, 65 370, 35 350" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 126 412 C 145 390, 170 370, 200 355" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 122 428 C 130 458, 145 490, 165 520" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <ellipse cx="120" cy="420" rx="18" ry="15" fill="url(#somaHaloGrad)" className="soma-halo-organic" />
                  <path ref={soma9Ref} d="M 114 414 Q 124 410 130 418 Q 134 426 126 432 Q 116 434 112 426 Q 110 418 114 414 Z" fill="#755B92" className="neuron-soma-organic" />
                </g>

                {/* NEURON 10 */}
                <g id="neuron-10">
                  <path d="M 619 132 C 615 90, 608 55, 600 20 M 608 55 C 590 35, 570 20, 550 5" stroke="#5E477D" strokeWidth="1.3" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 612 144 C 590 160, 565 175, 535 190" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <path d="M 626 144 C 645 160, 670 175, 700 190" stroke="#5E477D" strokeWidth="1.2" strokeLinecap="round" strokeOpacity="0.5" />
                  <ellipse cx="620" cy="140" rx="18" ry="15" fill="url(#somaHaloGrad)" className="soma-halo-organic" />
                  <path ref={soma10Ref} d="M 614 134 Q 624 130 630 138 Q 634 146 626 152 Q 616 154 612 146 Q 610 138 614 134 Z" fill="#755B92" className="neuron-soma-organic" />
                </g>

                {/* Synaptic Junction Micro-Sparks */}
                <circle cx="210" cy="270" r="1.6" fill="#FFFBF0" className="synapse-spark" />
                <circle cx="430" cy="255" r="1.6" fill="#FFE5B4" className="synapse-spark" />
                <circle cx="630" cy="265" r="1.8" fill="#FFFBF0" className="synapse-spark" />
                <circle cx="810" cy="130" r="1.6" fill="#E8DCF4" className="synapse-spark" />
                <circle cx="465" cy="470" r="1.6" fill="#FFE5B4" className="synapse-spark" />
                <circle cx="270" cy="530" r="1.6" fill="#E8DCF4" className="synapse-spark" />
                <circle cx="590" cy="450" r="1.6" fill="#FFFBF0" className="synapse-spark" />
                <circle cx="770" cy="510" r="1.6" fill="#FFE5B4" className="synapse-spark" />

                {/* ── ELECTRICAL SIGNALS (Luminous action potentials positioned at origin, moved via GPU transform) ── */}
                <g ref={sig1Ref} className="signal-pulse">
                  <circle cx="0" cy="0" r="6.0" fill="#FFECC8" opacity="0.3" />
                  <circle cx="0" cy="0" r="3.2" fill="#FFF8EC" />
                </g>
                <g ref={sig2Ref} className="signal-pulse">
                  <circle cx="0" cy="0" r="6.5" fill="#FFECC8" opacity="0.3" />
                  <circle cx="0" cy="0" r="3.4" fill="#FFECC8" />
                </g>
                <g ref={sig3Ref} className="signal-pulse">
                  <circle cx="0" cy="0" r="6.0" fill="#FFECC8" opacity="0.3" />
                  <circle cx="0" cy="0" r="3.2" fill="#FFF8EC" />
                </g>
                <g ref={sig4Ref} className="signal-pulse">
                  <circle cx="0" cy="0" r="6.0" fill="#EBD8FF" opacity="0.3" />
                  <circle cx="0" cy="0" r="3.2" fill="#EBD8FF" />
                </g>
                <g ref={sig5Ref} className="signal-pulse">
                  <circle cx="0" cy="0" r="6.0" fill="#FFECC8" opacity="0.3" />
                  <circle cx="0" cy="0" r="3.2" fill="#FFECC8" />
                </g>
                <g ref={sig6Ref} className="signal-pulse">
                  <circle cx="0" cy="0" r="5.5" fill="#FFECC8" opacity="0.3" />
                  <circle cx="0" cy="0" r="3.0" fill="#FFF8EC" />
                </g>
                <g ref={sig7Ref} className="signal-pulse">
                  <circle cx="0" cy="0" r="5.5" fill="#EBD8FF" opacity="0.3" />
                  <circle cx="0" cy="0" r="3.0" fill="#EBD8FF" />
                </g>
                <g ref={sig8Ref} className="signal-pulse">
                  <circle cx="0" cy="0" r="5.5" fill="#FFECC8" opacity="0.3" />
                  <circle cx="0" cy="0" r="3.0" fill="#FFECC8" />
                </g>
              </svg>

              {/* 3C: Foreground Giant Biological Structures (Gliding close past the camera lens) */}
              <svg ref={neuralForeRef} className="neural-plane neural-plane-fore" viewBox="0 0 1200 800" fill="none">
                {/* Massive Dendritic Trunk sweeping across top-left */}
                <path d="M -60 -40 C 40 40, 140 80, 260 110 C 340 130, 420 120, 520 85" stroke="#7A619A" strokeWidth="8.0" strokeLinecap="round" strokeOpacity="0.45" />
                <path d="M 260 110 C 310 160, 360 210, 430 250" stroke="#7A619A" strokeWidth="4.5" strokeLinecap="round" strokeOpacity="0.4" />
                <path d="M 260 110 C 220 180, 180 240, 120 290" stroke="#7A619A" strokeWidth="3.5" strokeLinecap="round" strokeOpacity="0.38" />

                {/* Massive Axon Cable sweeping down right-side */}
                <path d="M 1260 120 C 1140 220, 980 320, 940 440 C 900 560, 1020 680, 1260 760" stroke="#755B95" strokeWidth="6.5" strokeLinecap="round" strokeOpacity="0.42" />

                {/* Huge Multipolar Soma partially visible off-screen bottom-left */}
                <g transform="translate(-70, 720)">
                  <path d="M 0 0 C 80 -40, 180 -20, 260 30" stroke="#6F568E" strokeWidth="7.0" strokeLinecap="round" strokeOpacity="0.4" />
                  <path d="M 0 0 C 60 -100, 140 -160, 210 -220" stroke="#6F568E" strokeWidth="5.5" strokeLinecap="round" strokeOpacity="0.38" />
                  <ellipse cx="0" cy="0" rx="65" ry="50" fill="#6A5189" opacity="0.35" />
                </g>

                {/* Foreground axon sweeping lower quadrant */}
                <path d="M 280 840 C 480 750, 720 740, 960 810 C 1080 845, 1180 880, 1260 920" stroke="#664D82" strokeWidth="5.0" strokeLinecap="round" strokeOpacity="0.35" />
              </svg>

              {/* 3D: Micro Foreground (Floating vesicle particles and bio-luminescent micro-signals zooming past camera lens) */}
              <svg ref={neuralMicroRef} className="neural-plane neural-plane-micro" viewBox="0 0 1200 800" fill="none">
                <circle cx="150" cy="220" r="2.8" fill="#FFFBF2" opacity="0.85" />
                <circle cx="180" cy="540" r="3.4" fill="#FFE8C2" opacity="0.75" />
                <circle cx="340" cy="180" r="2.2" fill="#EBD8FF" opacity="0.8" />
                <circle cx="580" cy="260" r="3.8" fill="#FFF8EB" opacity="0.9" />
                <circle cx="720" cy="620" r="3.2" fill="#FFE8C2" opacity="0.85" />
                <circle cx="890" cy="310" r="2.5" fill="#EBD8FF" opacity="0.75" />
                <circle cx="1020" cy="460" r="4.0" fill="#FFFBF2" opacity="0.85" />
                <circle cx="450" cy="680" r="2.6" fill="#FFF8EB" opacity="0.8" />
                <circle cx="820" cy="160" r="3.0" fill="#FFECC8" opacity="0.85" />
              </svg>

            </div>

            {/* ── LAYER 5: THOUGHTS AT 3D DEPTHS (ALL DIRECTIONS, BALANCED 360°) ── */}
            <div className="interior-thoughts-layer" aria-live="polite">
              {NEURAL_THOUGHTS.map((t) => (
                <span
                  key={t.id}
                  ref={(el) => (thoughtRefs.current[t.id] = el)}
                  className={t.className}
                >
                  {t.text}
                </span>
              ))}
            </div>

          </div>

          {/* ── LAYER 4: MODERN EDITORIAL INTERRUPTIONS (Casual Sora typography) ── */}
          <div className="brain-editorial-layer" aria-live="polite">
            <div ref={enterBrainRef} className="brain-editorial-item editorial-pos-lower-left">
              <p className="brain-editorial-text">you are about to enter my brain.</p>
            </div>
            <div ref={sureRef} className="brain-editorial-item editorial-pos-above-center">
              <p className="brain-editorial-text text-short">are you sure?</p>
            </div>
            <div ref={reallySureRef} className="brain-editorial-item editorial-pos-mid-right">
              <p className="brain-editorial-text text-short">like... really sure?</p>
            </div>
            <div ref={mightBeBugsRef} className="brain-editorial-item editorial-pos-lower-right">
              <p className="brain-editorial-text">there might be bugs.</p>
            </div>
            <div ref={goingInRef} className="brain-editorial-item editorial-pos-center">
              <p className="brain-editorial-text text-going-in">okay. we're going in.</p>
            </div>
          </div>

          {/* ── "I AM INSIDE." BADGE (Inside moving neural world) ── */}
          <div ref={insideRef} className="interior-inside-badge" aria-hidden="true">
            <h2 className="inside-badge-title">I AM INSIDE.</h2>
            <span className="inside-badge-subtitle">NEURAL NETWORK ACTIVE</span>
          </div>

          {/* ── LAYER 7: BOTTOM WARNING SYSTEM (Subtle, Modern Minimal Typography) ── */}
          <div ref={warningRef} className="brain-bottom-warning" aria-live="polite">
            <div className="bottom-warning-pill">
              <span className="warning-indicator-dot" aria-hidden="true" />
              <div className="warning-text-container">
                <span ref={w1Ref} className="bottom-warning-text">brain access granted.</span>
                <span ref={w2Ref} className="bottom-warning-text">thought density increasing...</span>
                <span ref={w3Ref} className="bottom-warning-text">too many tabs open.</span>
                <span ref={w4Ref} className="bottom-warning-text">overthinking detected.</span>
                <span ref={w5Ref} className="bottom-warning-text">cognitive load: questionable.</span>
                <span ref={w6Ref} className="bottom-warning-text">this is probably fine.</span>
                <span ref={w7Ref} className="bottom-warning-text warning-overload">WARNING: TOO MANY THOUGHTS.</span>
              </div>
            </div>
          </div>

          {/* ── LAYER 8: VERY SHORT BLACK SCREEN FLASH (Brain crash interruption before collapse) ── */}
          <div ref={blackFlashRef} className="interior-black-flash" aria-hidden="true" />

          {/* ── LAYER 9: SILENCE BLACKOUT ── */}
          <div ref={blackoutRef} className="interior-silence-blackout" aria-hidden="true" />

        </div>

        {/* ── LAYER 10: THINGS I SOMEHOW KNOW (MagicBento + Immediate Thought Field) ── */}
        <div ref={bentoSectionRef} className="brain-bento-layer" aria-label="Things I Somehow Know">

          {/* Atmospheric ambient glow */}
          <div className="things-ambient-glow" aria-hidden="true" />

          {/* Immediate Thought Field (Active from first frame of collapse) */}
          <div ref={thoughtFieldRef} className="things-memory-field" aria-live="polite">
            {/* 24 Random Authentic Subconscious Thoughts */}
            {RANDOM_THOUGHTS.map((r) => (
              <div
                key={r.id}
                ref={(el) => (randomThoughtWrapperRefs.current[r.id] = el)}
                className="random-thought-wrapper"
              >
                <span
                  ref={(el) => (randomThoughtInnerRefs.current[r.id] = el)}
                  className="random-thought"
                >
                  {r.text}
                </span>
              </div>
            ))}

            {/* 6 Knowledge Thoughts (Extracted from cloud and fall into Bento card slots) */}
            {KNOWLEDGE_ITEMS.map((k) => (
              <div
                key={k.id}
                ref={(el) => (fallingThoughtWrapperRefs.current[k.id] = el)}
                className="falling-thought-wrapper"
              >
                <div
                  ref={(el) => (fallingTrailRefs.current[k.id] = el)}
                  className="falling-thought-trail"
                  aria-hidden="true"
                />
                <span
                  ref={(el) => (fallingThoughtInnerRefs.current[k.id] = el)}
                  className="falling-thought"
                >
                  {k.text}
                </span>
              </div>
            ))}
          </div>

          {/* Main Content: Editorial Header + MagicBento */}
          <div className="things-inner">
            <header ref={bentoHeaderRef} className="things-header">
              <span ref={bentoTagRef} className="things-tagline">WHAT OCCUPIES MY MIND</span>
              <h2 ref={bentoTitleRef} className="things-title">THINGS I SOMEHOW KNOW</h2>
              <p ref={bentoSubtitleRef} className="things-supporting-line">"I know a little about a lot of things."</p>
            </header>

            <div ref={bentoGridWrapRef} className="things-bento-container">
              <MagicBento />
            </div>
          </div>

        </div>

      </div>
    </section>
  );
}
